// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int num = Integer.parseInt(args[0]);
        int a = 0;
		double b;
		int big = 0;
		int small = 0;

		while(num>a)
		{
		b = (Math.random());
		if(b>0.5)
		{
			big = big +1;
		}
		else
		{
			small = small +1;
		}
		a = a +1;
		}

		System.out.println("> 0.5: " + big + " times");
		System.out.println("<= 0.5: " + small + " times");


	}
}
